-- ============================================================
-- Flor de Lis — número correlativo de reserva + creador
-- ============================================================
-- Número de reserva correlativo (nuestro ID a nivel reserva: 1, 2, 3, …),
-- asignado automáticamente por la base al insertar.
alter table public.reservas add column if not exists numero bigint generated by default as identity;
-- Nombre del usuario que cargó la reserva.
alter table public.reservas add column if not exists creado_por text;
